name: flutter_parsed_text
description: A Flutter package to parse text and make them into multiple Flutter Text widget.
version: 1.2.4
homepage: https://github.com/fayeed/flutter_parsed_text

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_text: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
